### ISSUE TITLE
can you update please?

### ISSUE THREAD

**Issue by z3r0b00t3r** [GuntranHoet/DwarfBot#1]
hi,
I would love to use your bot but aparently discord updated the requirements on some commands and it's not working.

I already tried to fix it myself but i'm afraid my knowledge is not enough to get it working again.

Could you be so kind as to update this amazing piece of technology?

ROCK AND STONE!!!!

**Comment by GuntranHoet** [comment]
My personal bot is running. So I've copy-pasted that code into this repo. That should do it.

Changes:
- Updated API which was no longer working
- Added more quotes
- Added more triggers
- Moved quotes and triggers to a 'data' folder

Rock and stone miner! ⛏️

**Comment by GuntranHoet** [comment]
@z3r0b00t3r can you confirm this update works for you?
If so, I'll close this issue 👍

**Comment by z3r0b00t3r** [comment]
> @z3r0b00t3r can you confirm this update works for you? If so, I'll close this issue 👍

Can confirm that is is working now. Thank you so much 👍
